//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace AWS_MVC_Web_Applicaiton.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PilesOfDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PilesOfDataEntities object using the connection string found in the 'PilesOfDataEntities' section of the application configuration file.
        /// </summary>
        public PilesOfDataEntities() : base("name=PilesOfDataEntities", "PilesOfDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PilesOfDataEntities object.
        /// </summary>
        public PilesOfDataEntities(string connectionString) : base(connectionString, "PilesOfDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PilesOfDataEntities object.
        /// </summary>
        public PilesOfDataEntities(EntityConnection connection) : base(connection, "PilesOfDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AwsInstanceStatus> AwsInstanceStatus1
        {
            get
            {
                if ((_AwsInstanceStatus1 == null))
                {
                    _AwsInstanceStatus1 = base.CreateObjectSet<AwsInstanceStatus>("AwsInstanceStatus1");
                }
                return _AwsInstanceStatus1;
            }
        }
        private ObjectSet<AwsInstanceStatus> _AwsInstanceStatus1;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AwsInstanceStatus1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAwsInstanceStatus1(AwsInstanceStatus awsInstanceStatus)
        {
            base.AddObject("AwsInstanceStatus1", awsInstanceStatus);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PilesOfDataModel", Name="AwsInstanceStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AwsInstanceStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AwsInstanceStatus object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static AwsInstanceStatus CreateAwsInstanceStatus(global::System.Guid id)
        {
            AwsInstanceStatus awsInstanceStatus = new AwsInstanceStatus();
            awsInstanceStatus.Id = id;
            return awsInstanceStatus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Stamp
        {
            get
            {
                return _Stamp;
            }
            set
            {
                OnStampChanging(value);
                ReportPropertyChanging("Stamp");
                _Stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stamp");
                OnStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _Stamp;
        partial void OnStampChanging(Nullable<global::System.DateTime> value);
        partial void OnStampChanged();

        #endregion
    
    }

    #endregion
    
}
